In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
from bs4 import BeautifulSoup
import time

In [2]:
driver = webdriver.Chrome()
url = "https://www.transfermarkt.com/premier-league/tabelle/wettbewerb/GB1/saison_id/2018"
driver.get(url)

In [3]:
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [4]:
# Wait for the page to load
time.sleep(5)  # Adjust as needed for your internet speed

In [5]:
table = soup.find('table', {'class':'items'})
rows = table.find_all('tr')

In [6]:
position = []
teams = []
played_games = []
wins = []
draws = []
losses = []
goals = []
goal_diff = []
points = []
team_ids = []

In [7]:
for row in rows[1:]:  # Skip the header row
    cols = row.find_all('td')
    if len(cols) > 0:
        position.append(cols[0].text.strip())  # Position
        teams.append(cols[2].text.strip())  # Team name (adjusted index)
        played_games.append(42)  # Games played (constant value)
        wins.append(cols[4].text.strip())  # Wins
        draws.append(cols[5].text.strip())  # Draws
        losses.append(cols[6].text.strip())  # Losses
        goals.append(cols[7].text.strip())  # Goals (For:Against)
        goal_diff.append(cols[8].text.strip())  # Goal difference (adjusted index)
        points.append(cols[9].text.strip())  # Points (adjusted index)

In [8]:
df = pd.DataFrame({
    'Position': position,
    'Team': teams,
    'Played': played_games,
    'Wins': wins,
    'Draws': draws,
    'Losses': losses,
    'Goals': goals,
    'Goal Difference': goal_diff,
    'Points': points
})

In [9]:
df.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points
0,1,Man City,42,32,2,4,95:23,72,98
1,2,Liverpool,42,30,7,1,89:22,67,97
2,3,Chelsea,42,21,9,8,63:39,24,72
3,4,Tottenham,42,23,2,13,67:39,28,71
4,5,Arsenal,42,21,7,10,73:51,22,70
5,6,Man Utd,42,19,9,10,65:54,11,66
6,7,Wolves,42,16,9,13,47:46,1,57
7,8,Everton,42,15,9,14,54:46,8,54
8,9,Leicester,42,15,7,16,51:48,3,52
9,10,West Ham,42,15,7,16,52:55,-3,52
10,11,Watford,42,14,8,16,52:59,-7,50
11,12,Crystal Palace,42,14,7,17,51:53,-2,49
12,13,Newcastle,42,12,9,17,42:48,-6,45
13,14,Bournemouth,42,13,6,19,56:70,-14,45
14,15,Burnley,42,11,7,20,45:68,-23,40
15,16,Southampton,42,9,12,17,45:65,-20,39
16,17,Brighton,42,9,9,20,35:60,-25,36
17,18,Cardiff,42,10,4,24,34:69,-35,34
18,19,Fulham,42,7,5,26,34:81,-47,26
19,20,Huddersfield,42,3,7,28,22:76,-54,16

In [10]:
df.replace({'Man City': 'Manchester City', 'Man Utd': 'Manchester United', 'Sheff Utd': 'Sheffield United', 'Sheff Wed': 'Sheffield Wednesday', 'Nottm Forest': 'Nottingham Forest', 'QPR': 'Queens Park Rangers', 'Wolves': 'Wolverhampton Wanderers', 'Leeds': 'Leeds United', 'Ipswich': 'Ipswich Town', 'Coventry': 'Coventry City', 'Wimbledon FC': 'Wimbledon', 'Tottenham': 'Tottenham Hotspur', 'Norwich': 'Norwich City', 'Blackburn': 'Blackburn Rovers', 'Newcastle': 'Newcastle United', 'West Ham': 'West Ham United', 'Leicester': 'Leicester City', 'Bolton': 'Bolton Wanderers', 'Derby': 'Derby County', 'Barnsley FC': 'Barnsley', 'Charlton': 'Charlton Athletic', 'Bradford': 'Bradford City', 'West Brom': 'West Bromwich Albion', 'Birmingham': 'Birmingham City', 'Wolves': 'Wolverhampton Wanderers', 'Wigan': 'Wigan Athletic', 'Swansea': 'Swansea City', 'Cardiff': 'Cardiff City', 'Huddersfield': 'Huddersfield Town', 'Brighton': 'Brighton & Hove Albion'}, inplace=True)

In [11]:
# Close the driver
driver.quit()

In [12]:
df.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points
0,1,Manchester City,42,32,2,4,95:23,72,98
1,2,Liverpool,42,30,7,1,89:22,67,97
2,3,Chelsea,42,21,9,8,63:39,24,72
3,4,Tottenham Hotspur,42,23,2,13,67:39,28,71
4,5,Arsenal,42,21,7,10,73:51,22,70
5,6,Manchester United,42,19,9,10,65:54,11,66
6,7,Wolverhampton Wanderers,42,16,9,13,47:46,1,57
7,8,Everton,42,15,9,14,54:46,8,54
8,9,Leicester City,42,15,7,16,51:48,3,52
9,10,West Ham United,42,15,7,16,52:55,-3,52
10,11,Watford,42,14,8,16,52:59,-7,50
11,12,Crystal Palace,42,14,7,17,51:53,-2,49
12,13,Newcastle United,42,12,9,17,42:48,-6,45
13,14,Bournemouth,42,13,6,19,56:70,-14,45
14,15,Burnley,42,11,7,20,45:68,-23,40
15,16,Southampton,42,9,12,17,45:65,-20,39
16,17,Brighton & Hove Albion,42,9,9,20,35:60,-25,36
17,18,Cardiff City,42,10,4,24,34:69,-35,34
18,19,Fulham,42,7,5,26,34:81,-47,26
19,20,Huddersfield Town,42,3,7,28,22:76,-54,16

In [13]:
df2 = pd.read_csv("EPL Matches 1992_1993_2023_2024.csv", index_col=0)

In [14]:
def add_managers_to_league_table(matches_df, league_table_df, season):
    """
    Add a column to the league table dataframe with managers who managed each team during a given season.
    
    Args:
        matches_df (pd.DataFrame): The dataframe containing match data.
        league_table_df (pd.DataFrame): The league table dataframe.
        season (str): The season to look for managers (e.g., '1992/1993').
    
    Returns:
        pd.DataFrame: The updated league table dataframe with a new 'Manager' column.
    """
    # Filter matches for the provided season
    season_matches = matches_df[matches_df['Season'] == season]

    # Create an empty dictionary to hold team names and their corresponding managers
    team_managers = {}

    # Loop through each match to get managers for the home and away teams
    for _, match in season_matches.iterrows():
        # For Home Team
        home_team = match['Home_Team']
        home_manager = match['Manager_Home']
        
        if home_team not in team_managers:
            team_managers[home_team] = set()  # Use a set to avoid duplicates
        team_managers[home_team].add(home_manager)

        # For Away Team
        away_team = match['Away_Team']
        away_manager = match['Manager_Away']
        
        if away_team not in team_managers:
            team_managers[away_team] = set()  # Use a set to avoid duplicates
        team_managers[away_team].add(away_manager)
    
    # Now, for each team in the league table, find their managers and add to the new column
    managers_list = []
    
    for _, row in league_table_df.iterrows():
        team_name = row['Team']
        
        if team_name in team_managers:
            # Convert the set of managers to a sorted list, then to a string
            managers = ', '.join(sorted(team_managers[team_name]))
        else:
            managers = 'Unknown'
        
        managers_list.append(managers)

    # Add the new column to the league table dataframe
    league_table_df['Manager'] = managers_list

    return league_table_df

In [15]:
updated_league_table = add_managers_to_league_table(df2, df, '2018/2019')
updated_league_table.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager
0,1,Manchester City,42,32,2,4,95:23,72,98,Pep Guardiola
1,2,Liverpool,42,30,7,1,89:22,67,97,Jurgen Klopp
2,3,Chelsea,42,21,9,8,63:39,24,72,Maurizio Sarri
3,4,Tottenham Hotspur,42,23,2,13,67:39,28,71,Mauricio Pochettino
4,5,Arsenal,42,21,7,10,73:51,22,70,Unai Emery
5,6,Manchester United,42,19,9,10,65:54,11,66,"Jose Mourinho, Ole Gunnar Solskjaer"
6,7,Wolverhampton Wanderers,42,16,9,13,47:46,1,57,Nuno Espirito Santo
7,8,Everton,42,15,9,14,54:46,8,54,Marco Silva
8,9,Leicester City,42,15,7,16,51:48,3,52,"Adam Sadler, Brendan Rodgers, Claude Puel"
9,10,West Ham United,42,15,7,16,52:55,-3,52,Manuel Pellegrini
10,11,Watford,42,14,8,16,52:59,-7,50,Javi Gracia
11,12,Crystal Palace,42,14,7,17,51:53,-2,49,Roy Hodgson
12,13,Newcastle United,42,12,9,17,42:48,-6,45,Rafael Benitez
13,14,Bournemouth,42,13,6,19,56:70,-14,45,Eddie Howe
14,15,Burnley,42,11,7,20,45:68,-23,40,Sean Dyche
15,16,Southampton,42,9,12,17,45:65,-20,39,"Kelvin Davis, Mark Hughes, Ralph Hasenhuttl"
16,17,Brighton & Hove Albion,42,9,9,20,35:60,-25,36,Chris Hughton
17,18,Cardiff City,42,10,4,24,34:69,-35,34,Neil Warnock
18,19,Fulham,42,7,5,26,34:81,-47,26,"Claudio Ranieri, Scott Parker, Slavisa Jokanovic"
19,20,Huddersfield Town,42,3,7,28,22:76,-54,16,"David Wagner, Jan Siewert, Mark Hudson"

In [16]:
df_manager = pd.read_csv("Manager History.csv")
team_id_mapping = dict(zip(df_manager['Team_Name'], df_manager['Team_ID']))
updated_league_table['Team_ID'] = updated_league_table['Team'].map(team_id_mapping)
updated_league_table['Season'] = '2018/2019'
updated_league_table = updated_league_table[['Season', 'Position', 'Team_ID', 'Team', 'Played', 'Wins', 'Draws', 'Losses', 'Goals', 'Goal Difference', 'Points', 'Manager']]
updated_league_table.head(23)

,Season,Position,Team_ID,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager
0,2018/2019,1,MCI,Manchester City,42,32,2,4,95:23,72,98,Pep Guardiola
1,2018/2019,2,LIV,Liverpool,42,30,7,1,89:22,67,97,Jurgen Klopp
2,2018/2019,3,CHE,Chelsea,42,21,9,8,63:39,24,72,Maurizio Sarri
3,2018/2019,4,THO,Tottenham Hotspur,42,23,2,13,67:39,28,71,Mauricio Pochettino
4,2018/2019,5,ARS,Arsenal,42,21,7,10,73:51,22,70,Unai Emery
5,2018/2019,6,MUN,Manchester United,42,19,9,10,65:54,11,66,"Jose Mourinho, Ole Gunnar Solskjaer"
6,2018/2019,7,WWA,Wolverhampton Wanderers,42,16,9,13,47:46,1,57,Nuno Espirito Santo
7,2018/2019,8,EVE,Everton,42,15,9,14,54:46,8,54,Marco Silva
8,2018/2019,9,LCI,Leicester City,42,15,7,16,51:48,3,52,"Adam Sadler, Brendan Rodgers, Claude Puel"
9,2018/2019,10,WHA,West Ham United,42,15,7,16,52:55,-3,52,Manuel Pellegrini
10,2018/2019,11,WAT,Watford,42,14,8,16,52:59,-7,50,Javi Gracia
11,2018/2019,12,CPA,Crystal Palace,42,14,7,17,51:53,-2,49,Roy Hodgson
12,2018/2019,13,NUN,Newcastle United,42,12,9,17,42:48,-6,45,Rafael Benitez
13,2018/2019,14,BOU,Bournemouth,42,13,6,19,56:70,-14,45,Eddie Howe
14,2018/2019,15,BUR,Burnley,42,11,7,20,45:68,-23,40,Sean Dyche
15,2018/2019,16,SOU,Southampton,42,9,12,17,45:65,-20,39,"Kelvin Davis, Mark Hughes, Ralph Hasenhuttl"
16,2018/2019,17,BHA,Brighton & Hove Albion,42,9,9,20,35:60,-25,36,Chris Hughton
17,2018/2019,18,CCI,Cardiff City,42,10,4,24,34:69,-35,34,Neil Warnock
18,2018/2019,19,FUL,Fulham,42,7,5,26,34:81,-47,26,"Claudio Ranieri, Scott Parker, Slavisa Jokanovic"
19,2018/2019,20,HTO,Huddersfield Town,42,3,7,28,22:76,-54,16,"David Wagner, Jan Siewert, Mark Hudson"

In [17]:
updated_league_table.to_csv('2018_2019 League Table.csv')