In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
from bs4 import BeautifulSoup
import time

In [2]:
driver = webdriver.Chrome()
url = "https://www.transfermarkt.com/premier-league/tabelle/wettbewerb/GB1/saison_id/2019"
driver.get(url)

In [3]:
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [4]:
# Wait for the page to load
time.sleep(5)  # Adjust as needed for your internet speed

In [5]:
table = soup.find('table', {'class':'items'})
rows = table.find_all('tr')

In [6]:
position = []
teams = []
played_games = []
wins = []
draws = []
losses = []
goals = []
goal_diff = []
points = []
team_ids = []

In [7]:
for row in rows[1:]:  # Skip the header row
    cols = row.find_all('td')
    if len(cols) > 0:
        position.append(cols[0].text.strip())  # Position
        teams.append(cols[2].text.strip())  # Team name (adjusted index)
        played_games.append(42)  # Games played (constant value)
        wins.append(cols[4].text.strip())  # Wins
        draws.append(cols[5].text.strip())  # Draws
        losses.append(cols[6].text.strip())  # Losses
        goals.append(cols[7].text.strip())  # Goals (For:Against)
        goal_diff.append(cols[8].text.strip())  # Goal difference (adjusted index)
        points.append(cols[9].text.strip())  # Points (adjusted index)

In [8]:
df = pd.DataFrame({
    'Position': position,
    'Team': teams,
    'Played': played_games,
    'Wins': wins,
    'Draws': draws,
    'Losses': losses,
    'Goals': goals,
    'Goal Difference': goal_diff,
    'Points': points
})

In [9]:
df.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points
0,1,Liverpool,42,32,3,3,85:33,52,99
1,2,Man City,42,26,3,9,102:35,67,81
2,3,Man Utd,42,18,12,8,66:36,30,66
3,4,Chelsea,42,20,6,12,69:54,15,66
4,5,Leicester,42,18,8,12,67:41,26,62
5,6,Tottenham,42,16,11,11,61:47,14,59
6,7,Wolves,42,15,14,9,51:40,11,59
7,8,Arsenal,42,14,14,10,56:48,8,56
8,9,Sheff Utd,42,14,12,12,39:39,0,54
9,10,Burnley,42,15,9,14,43:50,-7,54
10,11,Southampton,42,15,7,16,51:60,-9,52
11,12,Everton,42,13,10,15,44:56,-12,49
12,13,Newcastle,42,11,11,16,38:58,-20,44
13,14,Crystal Palace,42,11,10,17,31:50,-19,43
14,15,Brighton,42,9,14,15,39:54,-15,41
15,16,West Ham,42,10,9,19,49:62,-13,39
16,17,Aston Villa,42,9,8,21,41:67,-26,35
17,18,Bournemouth,42,9,7,22,40:65,-25,34
18,19,Watford,42,8,10,20,36:64,-28,34
19,20,Norwich,42,5,6,27,26:75,-49,21

In [10]:
df.replace({'Man City': 'Manchester City', 'Man Utd': 'Manchester United', 'Sheff Utd': 'Sheffield United', 'Sheff Wed': 'Sheffield Wednesday', 'Nottm Forest': 'Nottingham Forest', 'QPR': 'Queens Park Rangers', 'Wolves': 'Wolverhampton Wanderers', 'Leeds': 'Leeds United', 'Ipswich': 'Ipswich Town', 'Coventry': 'Coventry City', 'Wimbledon FC': 'Wimbledon', 'Tottenham': 'Tottenham Hotspur', 'Norwich': 'Norwich City', 'Blackburn': 'Blackburn Rovers', 'Newcastle': 'Newcastle United', 'West Ham': 'West Ham United', 'Leicester': 'Leicester City', 'Bolton': 'Bolton Wanderers', 'Derby': 'Derby County', 'Barnsley FC': 'Barnsley', 'Charlton': 'Charlton Athletic', 'Bradford': 'Bradford City', 'West Brom': 'West Bromwich Albion', 'Birmingham': 'Birmingham City', 'Wolves': 'Wolverhampton Wanderers', 'Wigan': 'Wigan Athletic', 'Swansea': 'Swansea City', 'Cardiff': 'Cardiff City', 'Huddersfield': 'Huddersfield Town', 'Brighton': 'Brighton & Hove Albion'}, inplace=True)

In [11]:
# Close the driver
driver.quit()

In [12]:
df.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points
0,1,Liverpool,42,32,3,3,85:33,52,99
1,2,Manchester City,42,26,3,9,102:35,67,81
2,3,Manchester United,42,18,12,8,66:36,30,66
3,4,Chelsea,42,20,6,12,69:54,15,66
4,5,Leicester City,42,18,8,12,67:41,26,62
5,6,Tottenham Hotspur,42,16,11,11,61:47,14,59
6,7,Wolverhampton Wanderers,42,15,14,9,51:40,11,59
7,8,Arsenal,42,14,14,10,56:48,8,56
8,9,Sheffield United,42,14,12,12,39:39,0,54
9,10,Burnley,42,15,9,14,43:50,-7,54
10,11,Southampton,42,15,7,16,51:60,-9,52
11,12,Everton,42,13,10,15,44:56,-12,49
12,13,Newcastle United,42,11,11,16,38:58,-20,44
13,14,Crystal Palace,42,11,10,17,31:50,-19,43
14,15,Brighton & Hove Albion,42,9,14,15,39:54,-15,41
15,16,West Ham United,42,10,9,19,49:62,-13,39
16,17,Aston Villa,42,9,8,21,41:67,-26,35
17,18,Bournemouth,42,9,7,22,40:65,-25,34
18,19,Watford,42,8,10,20,36:64,-28,34
19,20,Norwich City,42,5,6,27,26:75,-49,21

In [13]:
df2 = pd.read_csv("EPL Matches 1992_1993_2023_2024.csv", index_col=0)

In [14]:
def add_managers_to_league_table(matches_df, league_table_df, season):
    """
    Add a column to the league table dataframe with managers who managed each team during a given season.
    
    Args:
        matches_df (pd.DataFrame): The dataframe containing match data.
        league_table_df (pd.DataFrame): The league table dataframe.
        season (str): The season to look for managers (e.g., '1992/1993').
    
    Returns:
        pd.DataFrame: The updated league table dataframe with a new 'Manager' column.
    """
    # Filter matches for the provided season
    season_matches = matches_df[matches_df['Season'] == season]

    # Create an empty dictionary to hold team names and their corresponding managers
    team_managers = {}

    # Loop through each match to get managers for the home and away teams
    for _, match in season_matches.iterrows():
        # For Home Team
        home_team = match['Home_Team']
        home_manager = match['Manager_Home']
        
        if home_team not in team_managers:
            team_managers[home_team] = set()  # Use a set to avoid duplicates
        team_managers[home_team].add(home_manager)

        # For Away Team
        away_team = match['Away_Team']
        away_manager = match['Manager_Away']
        
        if away_team not in team_managers:
            team_managers[away_team] = set()  # Use a set to avoid duplicates
        team_managers[away_team].add(away_manager)
    
    # Now, for each team in the league table, find their managers and add to the new column
    managers_list = []
    
    for _, row in league_table_df.iterrows():
        team_name = row['Team']
        
        if team_name in team_managers:
            # Convert the set of managers to a sorted list, then to a string
            managers = ', '.join(sorted(team_managers[team_name]))
        else:
            managers = 'Unknown'
        
        managers_list.append(managers)

    # Add the new column to the league table dataframe
    league_table_df['Manager'] = managers_list

    return league_table_df

In [15]:
updated_league_table = add_managers_to_league_table(df2, df, '2019/2020')
updated_league_table.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager
0,1,Liverpool,42,32,3,3,85:33,52,99,Jurgen Klopp
1,2,Manchester City,42,26,3,9,102:35,67,81,Pep Guardiola
2,3,Manchester United,42,18,12,8,66:36,30,66,Ole Gunnar Solskjaer
3,4,Chelsea,42,20,6,12,69:54,15,66,Frank Lampard
4,5,Leicester City,42,18,8,12,67:41,26,62,Brendan Rodgers
5,6,Tottenham Hotspur,42,16,11,11,61:47,14,59,"Jose Mourinho, Mauricio Pochettino"
6,7,Wolverhampton Wanderers,42,15,14,9,51:40,11,59,Nuno Espirito Santo
7,8,Arsenal,42,14,14,10,56:48,8,56,"Freddie Ljungberg, Mikel Arteta, Unai Emery"
8,9,Sheffield United,42,14,12,12,39:39,0,54,Chris Wilder
9,10,Burnley,42,15,9,14,43:50,-7,54,Sean Dyche
10,11,Southampton,42,15,7,16,51:60,-9,52,Ralph Hasenhuttl
11,12,Everton,42,13,10,15,44:56,-12,49,"Carlo Ancelotti, Duncan Ferguson, Marco Silva"
12,13,Newcastle United,42,11,11,16,38:58,-20,44,Steve Bruce
13,14,Crystal Palace,42,11,10,17,31:50,-19,43,Roy Hodgson
14,15,Brighton & Hove Albion,42,9,14,15,39:54,-15,41,Graham Potter
15,16,West Ham United,42,10,9,19,49:62,-13,39,"David Moyes, Manuel Pellegrini"
16,17,Aston Villa,42,9,8,21,41:67,-26,35,Dean Smith
17,18,Bournemouth,42,9,7,22,40:65,-25,34,Eddie Howe
18,19,Watford,42,8,10,20,36:64,-28,34,"Hayden Mullins, Javi Gracia, Nigel Pearson, Qu..."
19,20,Norwich City,42,5,6,27,26:75,-49,21,Daniel Farke

In [16]:
df_manager = pd.read_csv("Manager History.csv")
team_id_mapping = dict(zip(df_manager['Team_Name'], df_manager['Team_ID']))
updated_league_table['Team_ID'] = updated_league_table['Team'].map(team_id_mapping)
updated_league_table['Season'] = '2019/2020'
updated_league_table = updated_league_table[['Season', 'Position', 'Team_ID', 'Team', 'Played', 'Wins', 'Draws', 'Losses', 'Goals', 'Goal Difference', 'Points', 'Manager']]
updated_league_table.head(23)

,Season,Position,Team_ID,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager
0,2019/2020,1,LIV,Liverpool,42,32,3,3,85:33,52,99,Jurgen Klopp
1,2019/2020,2,MCI,Manchester City,42,26,3,9,102:35,67,81,Pep Guardiola
2,2019/2020,3,MUN,Manchester United,42,18,12,8,66:36,30,66,Ole Gunnar Solskjaer
3,2019/2020,4,CHE,Chelsea,42,20,6,12,69:54,15,66,Frank Lampard
4,2019/2020,5,LCI,Leicester City,42,18,8,12,67:41,26,62,Brendan Rodgers
5,2019/2020,6,THO,Tottenham Hotspur,42,16,11,11,61:47,14,59,"Jose Mourinho, Mauricio Pochettino"
6,2019/2020,7,WWA,Wolverhampton Wanderers,42,15,14,9,51:40,11,59,Nuno Espirito Santo
7,2019/2020,8,ARS,Arsenal,42,14,14,10,56:48,8,56,"Freddie Ljungberg, Mikel Arteta, Unai Emery"
8,2019/2020,9,SHU,Sheffield United,42,14,12,12,39:39,0,54,Chris Wilder
9,2019/2020,10,BUR,Burnley,42,15,9,14,43:50,-7,54,Sean Dyche
10,2019/2020,11,SOU,Southampton,42,15,7,16,51:60,-9,52,Ralph Hasenhuttl
11,2019/2020,12,EVE,Everton,42,13,10,15,44:56,-12,49,"Carlo Ancelotti, Duncan Ferguson, Marco Silva"
12,2019/2020,13,NUN,Newcastle United,42,11,11,16,38:58,-20,44,Steve Bruce
13,2019/2020,14,CPA,Crystal Palace,42,11,10,17,31:50,-19,43,Roy Hodgson
14,2019/2020,15,BHA,Brighton & Hove Albion,42,9,14,15,39:54,-15,41,Graham Potter
15,2019/2020,16,WHA,West Ham United,42,10,9,19,49:62,-13,39,"David Moyes, Manuel Pellegrini"
16,2019/2020,17,AVI,Aston Villa,42,9,8,21,41:67,-26,35,Dean Smith
17,2019/2020,18,BOU,Bournemouth,42,9,7,22,40:65,-25,34,Eddie Howe
18,2019/2020,19,WAT,Watford,42,8,10,20,36:64,-28,34,"Hayden Mullins, Javi Gracia, Nigel Pearson, Qu..."
19,2019/2020,20,NCI,Norwich City,42,5,6,27,26:75,-49,21,Daniel Farke

In [17]:
updated_league_table.to_csv('2019_2020 League Table.csv')