In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
from bs4 import BeautifulSoup
import time

In [2]:
driver = webdriver.Chrome()
url = "https://www.transfermarkt.com/premier-league/tabelle/wettbewerb/GB1/saison_id/2009"
driver.get(url)

In [3]:
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [4]:
# Wait for the page to load
time.sleep(5)  # Adjust as needed for your internet speed

In [5]:
table = soup.find('table', {'class':'items'})
rows = table.find_all('tr')

In [6]:
position = []
teams = []
played_games = []
wins = []
draws = []
losses = []
goals = []
goal_diff = []
points = []
team_ids = []

In [7]:
for row in rows[1:]:  # Skip the header row
    cols = row.find_all('td')
    if len(cols) > 0:
        position.append(cols[0].text.strip())  # Position
        teams.append(cols[2].text.strip())  # Team name (adjusted index)
        played_games.append(42)  # Games played (constant value)
        wins.append(cols[4].text.strip())  # Wins
        draws.append(cols[5].text.strip())  # Draws
        losses.append(cols[6].text.strip())  # Losses
        goals.append(cols[7].text.strip())  # Goals (For:Against)
        goal_diff.append(cols[8].text.strip())  # Goal difference (adjusted index)
        points.append(cols[9].text.strip())  # Points (adjusted index)

In [8]:
df = pd.DataFrame({
    'Position': position,
    'Team': teams,
    'Played': played_games,
    'Wins': wins,
    'Draws': draws,
    'Losses': losses,
    'Goals': goals,
    'Goal Difference': goal_diff,
    'Points': points
})

In [9]:
df.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points
0,1,Chelsea,42,27,5,6,103:32,71,86
1,2,Man Utd,42,27,4,7,86:28,58,85
2,3,Arsenal,42,23,6,9,83:41,42,75
3,4,Tottenham,42,21,7,10,67:41,26,70
4,5,Man City,42,18,13,7,73:45,28,67
5,6,Aston Villa,42,17,13,8,52:39,13,64
6,7,Liverpool,42,18,9,11,61:35,26,63
7,8,Everton,42,16,13,9,60:49,11,61
8,9,Birmingham,42,13,11,14,38:47,-9,50
9,10,Blackburn,42,13,11,14,41:55,-14,50
10,11,Stoke City,42,11,14,13,34:48,-14,47
11,12,Fulham,42,12,10,16,39:46,-7,46
12,13,Sunderland,42,11,11,16,48:56,-8,44
13,14,Bolton,42,10,9,19,42:67,-25,39
14,15,Wolves,42,9,11,18,32:56,-24,38
15,16,Wigan,42,9,9,20,37:79,-42,36
16,17,West Ham,42,8,11,19,47:66,-19,35
17,18,Burnley,42,8,6,24,42:82,-40,30
18,19,Hull City,42,6,12,20,34:75,-41,30
19,20,Portsmouth,42,7,7,24,34:66,-32,19

In [10]:
df.replace({'Man City': 'Manchester City', 'Man Utd': 'Manchester United', 'Sheff Utd': 'Sheffield United', 'Sheff Wed': 'Sheffield Wednesday', 'Nottm Forest': 'Nottingham Forest', 'QPR': 'Queens Park Rangers', 'Wolves': 'Wolverhampton Wanderers', 'Leeds': 'Leeds United', 'Ipswich': 'Ipswich Town', 'Coventry': 'Coventry City', 'Wimbledon FC': 'Wimbledon', 'Tottenham': 'Tottenham Hotspur', 'Norwich': 'Norwich City', 'Blackburn': 'Blackburn Rovers', 'Newcastle': 'Newcastle United', 'West Ham': 'West Ham United', 'Leicester': 'Leicester City', 'Bolton': 'Bolton Wanderers', 'Derby': 'Derby County', 'Barnsley FC': 'Barnsley', 'Charlton': 'Charlton Athletic', 'Bradford': 'Bradford City', 'West Brom': 'West Bromwich Albion', 'Birmingham': 'Birmingham City', 'Wolves': 'Wolverhampton Wanderers', 'Wigan': 'Wigan Athletic'}, inplace=True)

In [11]:
# Close the driver
driver.quit()

In [12]:
df.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points
0,1,Chelsea,42,27,5,6,103:32,71,86
1,2,Manchester United,42,27,4,7,86:28,58,85
2,3,Arsenal,42,23,6,9,83:41,42,75
3,4,Tottenham Hotspur,42,21,7,10,67:41,26,70
4,5,Manchester City,42,18,13,7,73:45,28,67
5,6,Aston Villa,42,17,13,8,52:39,13,64
6,7,Liverpool,42,18,9,11,61:35,26,63
7,8,Everton,42,16,13,9,60:49,11,61
8,9,Birmingham City,42,13,11,14,38:47,-9,50
9,10,Blackburn Rovers,42,13,11,14,41:55,-14,50
10,11,Stoke City,42,11,14,13,34:48,-14,47
11,12,Fulham,42,12,10,16,39:46,-7,46
12,13,Sunderland,42,11,11,16,48:56,-8,44
13,14,Bolton Wanderers,42,10,9,19,42:67,-25,39
14,15,Wolverhampton Wanderers,42,9,11,18,32:56,-24,38
15,16,Wigan Athletic,42,9,9,20,37:79,-42,36
16,17,West Ham United,42,8,11,19,47:66,-19,35
17,18,Burnley,42,8,6,24,42:82,-40,30
18,19,Hull City,42,6,12,20,34:75,-41,30
19,20,Portsmouth,42,7,7,24,34:66,-32,19

In [13]:
df2 = pd.read_csv("EPL Matches 1992_1993_2023_2024.csv", index_col=0)

In [14]:
def add_managers_to_league_table(matches_df, league_table_df, season):
    """
    Add a column to the league table dataframe with managers who managed each team during a given season.
    
    Args:
        matches_df (pd.DataFrame): The dataframe containing match data.
        league_table_df (pd.DataFrame): The league table dataframe.
        season (str): The season to look for managers (e.g., '1992/1993').
    
    Returns:
        pd.DataFrame: The updated league table dataframe with a new 'Manager' column.
    """
    # Filter matches for the provided season
    season_matches = matches_df[matches_df['Season'] == season]

    # Create an empty dictionary to hold team names and their corresponding managers
    team_managers = {}

    # Loop through each match to get managers for the home and away teams
    for _, match in season_matches.iterrows():
        # For Home Team
        home_team = match['Home_Team']
        home_manager = match['Manager_Home']
        
        if home_team not in team_managers:
            team_managers[home_team] = set()  # Use a set to avoid duplicates
        team_managers[home_team].add(home_manager)

        # For Away Team
        away_team = match['Away_Team']
        away_manager = match['Manager_Away']
        
        if away_team not in team_managers:
            team_managers[away_team] = set()  # Use a set to avoid duplicates
        team_managers[away_team].add(away_manager)
    
    # Now, for each team in the league table, find their managers and add to the new column
    managers_list = []
    
    for _, row in league_table_df.iterrows():
        team_name = row['Team']
        
        if team_name in team_managers:
            # Convert the set of managers to a sorted list, then to a string
            managers = ', '.join(sorted(team_managers[team_name]))
        else:
            managers = 'Unknown'
        
        managers_list.append(managers)

    # Add the new column to the league table dataframe
    league_table_df['Manager'] = managers_list

    return league_table_df

In [15]:
updated_league_table = add_managers_to_league_table(df2, df, '2009/2010')
updated_league_table.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager
0,1,Chelsea,42,27,5,6,103:32,71,86,Carlo Ancelotti
1,2,Manchester United,42,27,4,7,86:28,58,85,Sir Alex Ferguson
2,3,Arsenal,42,23,6,9,83:41,42,75,Arsene Wenger
3,4,Tottenham Hotspur,42,21,7,10,67:41,26,70,Harry Redknapp
4,5,Manchester City,42,18,13,7,73:45,28,67,"Mark Hughes, Roberto Mancini"
5,6,Aston Villa,42,17,13,8,52:39,13,64,Martin O'Neill
6,7,Liverpool,42,18,9,11,61:35,26,63,Rafael Benitez
7,8,Everton,42,16,13,9,60:49,11,61,David Moyes
8,9,Birmingham City,42,13,11,14,38:47,-9,50,Alex McLeish
9,10,Blackburn Rovers,42,13,11,14,41:55,-14,50,Sam Allardyce
10,11,Stoke City,42,11,14,13,34:48,-14,47,Tony Pulis
11,12,Fulham,42,12,10,16,39:46,-7,46,Roy Hodgson
12,13,Sunderland,42,11,11,16,48:56,-8,44,Steve Bruce
13,14,Bolton Wanderers,42,10,9,19,42:67,-25,39,"Gary Megson, Owen Coyle"
14,15,Wolverhampton Wanderers,42,9,11,18,32:56,-24,38,Mick McCarthy
15,16,Wigan Athletic,42,9,9,20,37:79,-42,36,Roberto Martinez
16,17,West Ham United,42,8,11,19,47:66,-19,35,Gianfranco Zola
17,18,Burnley,42,8,6,24,42:82,-40,30,"Brian Laws, Owen Coyle"
18,19,Hull City,42,6,12,20,34:75,-41,30,"Iain Dowie, Phil Brown"
19,20,Portsmouth,42,7,7,24,34:66,-32,19,"Avram Grant, Paul Hart"

In [16]:
df_manager = pd.read_csv("Manager History.csv")
team_id_mapping = dict(zip(df_manager['Team_Name'], df_manager['Team_ID']))
updated_league_table['Team_ID'] = updated_league_table['Team'].map(team_id_mapping)
updated_league_table['Season'] = '2009/2010'
updated_league_table = updated_league_table[['Season', 'Position', 'Team_ID', 'Team', 'Played', 'Wins', 'Draws', 'Losses', 'Goals', 'Goal Difference', 'Points', 'Manager']]
updated_league_table.head(23)

,Season,Position,Team_ID,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager
0,2009/2010,1,CHE,Chelsea,42,27,5,6,103:32,71,86,Carlo Ancelotti
1,2009/2010,2,MUN,Manchester United,42,27,4,7,86:28,58,85,Sir Alex Ferguson
2,2009/2010,3,ARS,Arsenal,42,23,6,9,83:41,42,75,Arsene Wenger
3,2009/2010,4,THO,Tottenham Hotspur,42,21,7,10,67:41,26,70,Harry Redknapp
4,2009/2010,5,MCI,Manchester City,42,18,13,7,73:45,28,67,"Mark Hughes, Roberto Mancini"
5,2009/2010,6,AVI,Aston Villa,42,17,13,8,52:39,13,64,Martin O'Neill
6,2009/2010,7,LIV,Liverpool,42,18,9,11,61:35,26,63,Rafael Benitez
7,2009/2010,8,EVE,Everton,42,16,13,9,60:49,11,61,David Moyes
8,2009/2010,9,BCI,Birmingham City,42,13,11,14,38:47,-9,50,Alex McLeish
9,2009/2010,10,BRO,Blackburn Rovers,42,13,11,14,41:55,-14,50,Sam Allardyce
10,2009/2010,11,SCI,Stoke City,42,11,14,13,34:48,-14,47,Tony Pulis
11,2009/2010,12,FUL,Fulham,42,12,10,16,39:46,-7,46,Roy Hodgson
12,2009/2010,13,SUN,Sunderland,42,11,11,16,48:56,-8,44,Steve Bruce
13,2009/2010,14,BWA,Bolton Wanderers,42,10,9,19,42:67,-25,39,"Gary Megson, Owen Coyle"
14,2009/2010,15,WWA,Wolverhampton Wanderers,42,9,11,18,32:56,-24,38,Mick McCarthy
15,2009/2010,16,WGA,Wigan Athletic,42,9,9,20,37:79,-42,36,Roberto Martinez
16,2009/2010,17,WHA,West Ham United,42,8,11,19,47:66,-19,35,Gianfranco Zola
17,2009/2010,18,BUR,Burnley,42,8,6,24,42:82,-40,30,"Brian Laws, Owen Coyle"
18,2009/2010,19,HCI,Hull City,42,6,12,20,34:75,-41,30,"Iain Dowie, Phil Brown"
19,2009/2010,20,POR,Portsmouth,42,7,7,24,34:66,-32,19,"Avram Grant, Paul Hart"

In [17]:
updated_league_table.to_csv('2009_2010 League Table.csv')