In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
from bs4 import BeautifulSoup
import time

In [2]:
driver = webdriver.Chrome()
url = "https://www.transfermarkt.com/premier-league/tabelle/wettbewerb/GB1/saison_id/2011"
driver.get(url)

In [3]:
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [4]:
# Wait for the page to load
time.sleep(5)  # Adjust as needed for your internet speed

In [5]:
table = soup.find('table', {'class':'items'})
rows = table.find_all('tr')

In [6]:
position = []
teams = []
played_games = []
wins = []
draws = []
losses = []
goals = []
goal_diff = []
points = []
team_ids = []

In [7]:
for row in rows[1:]:  # Skip the header row
    cols = row.find_all('td')
    if len(cols) > 0:
        position.append(cols[0].text.strip())  # Position
        teams.append(cols[2].text.strip())  # Team name (adjusted index)
        played_games.append(42)  # Games played (constant value)
        wins.append(cols[4].text.strip())  # Wins
        draws.append(cols[5].text.strip())  # Draws
        losses.append(cols[6].text.strip())  # Losses
        goals.append(cols[7].text.strip())  # Goals (For:Against)
        goal_diff.append(cols[8].text.strip())  # Goal difference (adjusted index)
        points.append(cols[9].text.strip())  # Points (adjusted index)

In [8]:
df = pd.DataFrame({
    'Position': position,
    'Team': teams,
    'Played': played_games,
    'Wins': wins,
    'Draws': draws,
    'Losses': losses,
    'Goals': goals,
    'Goal Difference': goal_diff,
    'Points': points
})

In [9]:
df.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points
0,1,Man City,42,28,5,5,93:29,64,89
1,2,Man Utd,42,28,5,5,89:33,56,89
2,3,Arsenal,42,21,7,10,74:49,25,70
3,4,Tottenham,42,20,9,9,66:41,25,69
4,5,Newcastle,42,19,8,11,56:51,5,65
5,6,Chelsea,42,18,10,10,65:46,19,64
6,7,Everton,42,15,11,12,50:40,10,56
7,8,Liverpool,42,14,10,14,47:40,7,52
8,9,Fulham,42,14,10,14,48:51,-3,52
9,10,West Brom,42,13,8,17,45:52,-7,47
10,11,Swansea,42,12,11,15,44:51,-7,47
11,12,Norwich,42,12,11,15,52:66,-14,47
12,13,Sunderland,42,11,12,15,45:46,-1,45
13,14,Stoke City,42,11,12,15,36:53,-17,45
14,15,Wigan,42,11,10,17,42:62,-20,43
15,16,Aston Villa,42,7,17,14,37:53,-16,38
16,17,QPR,42,10,7,21,43:66,-23,37
17,18,Bolton,42,10,6,22,46:77,-31,36
18,19,Blackburn,42,8,7,23,48:78,-30,31
19,20,Wolves,42,5,10,23,40:82,-42,25

In [10]:
df.replace({'Man City': 'Manchester City', 'Man Utd': 'Manchester United', 'Sheff Utd': 'Sheffield United', 'Sheff Wed': 'Sheffield Wednesday', 'Nottm Forest': 'Nottingham Forest', 'QPR': 'Queens Park Rangers', 'Wolves': 'Wolverhampton Wanderers', 'Leeds': 'Leeds United', 'Ipswich': 'Ipswich Town', 'Coventry': 'Coventry City', 'Wimbledon FC': 'Wimbledon', 'Tottenham': 'Tottenham Hotspur', 'Norwich': 'Norwich City', 'Blackburn': 'Blackburn Rovers', 'Newcastle': 'Newcastle United', 'West Ham': 'West Ham United', 'Leicester': 'Leicester City', 'Bolton': 'Bolton Wanderers', 'Derby': 'Derby County', 'Barnsley FC': 'Barnsley', 'Charlton': 'Charlton Athletic', 'Bradford': 'Bradford City', 'West Brom': 'West Bromwich Albion', 'Birmingham': 'Birmingham City', 'Wolves': 'Wolverhampton Wanderers', 'Wigan': 'Wigan Athletic', 'Swansea': 'Swansea City'}, inplace=True)

In [11]:
# Close the driver
driver.quit()

In [12]:
df.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points
0,1,Manchester City,42,28,5,5,93:29,64,89
1,2,Manchester United,42,28,5,5,89:33,56,89
2,3,Arsenal,42,21,7,10,74:49,25,70
3,4,Tottenham Hotspur,42,20,9,9,66:41,25,69
4,5,Newcastle United,42,19,8,11,56:51,5,65
5,6,Chelsea,42,18,10,10,65:46,19,64
6,7,Everton,42,15,11,12,50:40,10,56
7,8,Liverpool,42,14,10,14,47:40,7,52
8,9,Fulham,42,14,10,14,48:51,-3,52
9,10,West Bromwich Albion,42,13,8,17,45:52,-7,47
10,11,Swansea City,42,12,11,15,44:51,-7,47
11,12,Norwich City,42,12,11,15,52:66,-14,47
12,13,Sunderland,42,11,12,15,45:46,-1,45
13,14,Stoke City,42,11,12,15,36:53,-17,45
14,15,Wigan Athletic,42,11,10,17,42:62,-20,43
15,16,Aston Villa,42,7,17,14,37:53,-16,38
16,17,Queens Park Rangers,42,10,7,21,43:66,-23,37
17,18,Bolton Wanderers,42,10,6,22,46:77,-31,36
18,19,Blackburn Rovers,42,8,7,23,48:78,-30,31
19,20,Wolverhampton Wanderers,42,5,10,23,40:82,-42,25

In [13]:
df2 = pd.read_csv("EPL Matches 1992_1993_2023_2024.csv", index_col=0)

In [14]:
def add_managers_to_league_table(matches_df, league_table_df, season):
    """
    Add a column to the league table dataframe with managers who managed each team during a given season.
    
    Args:
        matches_df (pd.DataFrame): The dataframe containing match data.
        league_table_df (pd.DataFrame): The league table dataframe.
        season (str): The season to look for managers (e.g., '1992/1993').
    
    Returns:
        pd.DataFrame: The updated league table dataframe with a new 'Manager' column.
    """
    # Filter matches for the provided season
    season_matches = matches_df[matches_df['Season'] == season]

    # Create an empty dictionary to hold team names and their corresponding managers
    team_managers = {}

    # Loop through each match to get managers for the home and away teams
    for _, match in season_matches.iterrows():
        # For Home Team
        home_team = match['Home_Team']
        home_manager = match['Manager_Home']
        
        if home_team not in team_managers:
            team_managers[home_team] = set()  # Use a set to avoid duplicates
        team_managers[home_team].add(home_manager)

        # For Away Team
        away_team = match['Away_Team']
        away_manager = match['Manager_Away']
        
        if away_team not in team_managers:
            team_managers[away_team] = set()  # Use a set to avoid duplicates
        team_managers[away_team].add(away_manager)
    
    # Now, for each team in the league table, find their managers and add to the new column
    managers_list = []
    
    for _, row in league_table_df.iterrows():
        team_name = row['Team']
        
        if team_name in team_managers:
            # Convert the set of managers to a sorted list, then to a string
            managers = ', '.join(sorted(team_managers[team_name]))
        else:
            managers = 'Unknown'
        
        managers_list.append(managers)

    # Add the new column to the league table dataframe
    league_table_df['Manager'] = managers_list

    return league_table_df

In [15]:
updated_league_table = add_managers_to_league_table(df2, df, '2011/2012')
updated_league_table.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager
0,1,Manchester City,42,28,5,5,93:29,64,89,Roberto Mancini
1,2,Manchester United,42,28,5,5,89:33,56,89,Sir Alex Ferguson
2,3,Arsenal,42,21,7,10,74:49,25,70,Arsene Wenger
3,4,Tottenham Hotspur,42,20,9,9,66:41,25,69,Harry Redknapp
4,5,Newcastle United,42,19,8,11,56:51,5,65,Alan Pardew
5,6,Chelsea,42,18,10,10,65:46,19,64,"Andre Villas-Boas, Roberto Di Matteo"
6,7,Everton,42,15,11,12,50:40,10,56,David Moyes
7,8,Liverpool,42,14,10,14,47:40,7,52,Sir Kenny Dalglish
8,9,Fulham,42,14,10,14,48:51,-3,52,Martin Jol
9,10,West Bromwich Albion,42,13,8,17,45:52,-7,47,Roy Hodgson
10,11,Swansea City,42,12,11,15,44:51,-7,47,Brendan Rodgers
11,12,Norwich City,42,12,11,15,52:66,-14,47,Paul Lambert
12,13,Sunderland,42,11,12,15,45:46,-1,45,"Eric Black, Martin O'Neill, Steve Bruce"
13,14,Stoke City,42,11,12,15,36:53,-17,45,Tony Pulis
14,15,Wigan Athletic,42,11,10,17,42:62,-20,43,Roberto Martinez
15,16,Aston Villa,42,7,17,14,37:53,-16,38,Alex McLeish
16,17,Queens Park Rangers,42,10,7,21,43:66,-23,37,"Mark Hughes, Neil Warnock"
17,18,Bolton Wanderers,42,10,6,22,46:77,-31,36,Owen Coyle
18,19,Blackburn Rovers,42,8,7,23,48:78,-30,31,Steve Kean
19,20,Wolverhampton Wanderers,42,5,10,23,40:82,-42,25,"Mick McCarthy, Stale Solbakken, Terry Connor"

In [16]:
df_manager = pd.read_csv("Manager History.csv")
team_id_mapping = dict(zip(df_manager['Team_Name'], df_manager['Team_ID']))
updated_league_table['Team_ID'] = updated_league_table['Team'].map(team_id_mapping)
updated_league_table['Season'] = '2011/2012'
updated_league_table = updated_league_table[['Season', 'Position', 'Team_ID', 'Team', 'Played', 'Wins', 'Draws', 'Losses', 'Goals', 'Goal Difference', 'Points', 'Manager']]
updated_league_table.head(23)

,Season,Position,Team_ID,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager
0,2011/2012,1,MCI,Manchester City,42,28,5,5,93:29,64,89,Roberto Mancini
1,2011/2012,2,MUN,Manchester United,42,28,5,5,89:33,56,89,Sir Alex Ferguson
2,2011/2012,3,ARS,Arsenal,42,21,7,10,74:49,25,70,Arsene Wenger
3,2011/2012,4,THO,Tottenham Hotspur,42,20,9,9,66:41,25,69,Harry Redknapp
4,2011/2012,5,NUN,Newcastle United,42,19,8,11,56:51,5,65,Alan Pardew
5,2011/2012,6,CHE,Chelsea,42,18,10,10,65:46,19,64,"Andre Villas-Boas, Roberto Di Matteo"
6,2011/2012,7,EVE,Everton,42,15,11,12,50:40,10,56,David Moyes
7,2011/2012,8,LIV,Liverpool,42,14,10,14,47:40,7,52,Sir Kenny Dalglish
8,2011/2012,9,FUL,Fulham,42,14,10,14,48:51,-3,52,Martin Jol
9,2011/2012,10,WBR,West Bromwich Albion,42,13,8,17,45:52,-7,47,Roy Hodgson
10,2011/2012,11,SWA,Swansea City,42,12,11,15,44:51,-7,47,Brendan Rodgers
11,2011/2012,12,NCI,Norwich City,42,12,11,15,52:66,-14,47,Paul Lambert
12,2011/2012,13,SUN,Sunderland,42,11,12,15,45:46,-1,45,"Eric Black, Martin O'Neill, Steve Bruce"
13,2011/2012,14,SCI,Stoke City,42,11,12,15,36:53,-17,45,Tony Pulis
14,2011/2012,15,WGA,Wigan Athletic,42,11,10,17,42:62,-20,43,Roberto Martinez
15,2011/2012,16,AVI,Aston Villa,42,7,17,14,37:53,-16,38,Alex McLeish
16,2011/2012,17,QPA,Queens Park Rangers,42,10,7,21,43:66,-23,37,"Mark Hughes, Neil Warnock"
17,2011/2012,18,BWA,Bolton Wanderers,42,10,6,22,46:77,-31,36,Owen Coyle
18,2011/2012,19,BRO,Blackburn Rovers,42,8,7,23,48:78,-30,31,Steve Kean
19,2011/2012,20,WWA,Wolverhampton Wanderers,42,5,10,23,40:82,-42,25,"Mick McCarthy, Stale Solbakken, Terry Connor"

In [17]:
updated_league_table.to_csv('2011_2012 League Table.csv')