In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
import pandas as pd
from bs4 import BeautifulSoup
import time

In [2]:
driver = webdriver.Chrome()
url = "https://www.transfermarkt.com/premier-league/tabelle/wettbewerb/GB1/saison_id/2020"
driver.get(url)

In [3]:
soup = BeautifulSoup(driver.page_source, 'html.parser')

In [4]:
# Wait for the page to load
time.sleep(5)  # Adjust as needed for your internet speed

In [5]:
table = soup.find('table', {'class':'items'})
rows = table.find_all('tr')

In [6]:
position = []
teams = []
played_games = []
wins = []
draws = []
losses = []
goals = []
goal_diff = []
points = []
team_ids = []

In [7]:
for row in rows[1:]:  # Skip the header row
    cols = row.find_all('td')
    if len(cols) > 0:
        position.append(cols[0].text.strip())  # Position
        teams.append(cols[2].text.strip())  # Team name (adjusted index)
        played_games.append(42)  # Games played (constant value)
        wins.append(cols[4].text.strip())  # Wins
        draws.append(cols[5].text.strip())  # Draws
        losses.append(cols[6].text.strip())  # Losses
        goals.append(cols[7].text.strip())  # Goals (For:Against)
        goal_diff.append(cols[8].text.strip())  # Goal difference (adjusted index)
        points.append(cols[9].text.strip())  # Points (adjusted index)

In [8]:
df = pd.DataFrame({
    'Position': position,
    'Team': teams,
    'Played': played_games,
    'Wins': wins,
    'Draws': draws,
    'Losses': losses,
    'Goals': goals,
    'Goal Difference': goal_diff,
    'Points': points
})

In [9]:
df.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points
0,1,Man City,42,27,5,6,83:32,51,86
1,2,Man Utd,42,21,11,6,73:44,29,74
2,3,Liverpool,42,20,9,9,68:42,26,69
3,4,Chelsea,42,19,10,9,58:36,22,67
4,5,Leicester,42,20,6,12,68:50,18,66
5,6,West Ham,42,19,8,11,62:47,15,65
6,7,Tottenham,42,18,8,12,68:45,23,62
7,8,Arsenal,42,18,7,13,55:39,16,61
8,9,Leeds,42,18,5,15,62:54,8,59
9,10,Everton,42,17,8,13,47:48,-1,59
10,11,Aston Villa,42,16,7,15,55:46,9,55
11,12,Newcastle,42,12,9,17,46:62,-16,45
12,13,Wolves,42,12,9,17,36:52,-16,45
13,14,Crystal Palace,42,12,8,18,41:66,-25,44
14,15,Southampton,42,12,7,19,47:68,-21,43
15,16,Brighton,42,9,14,15,40:46,-6,41
16,17,Burnley,42,10,9,19,33:55,-22,39
17,18,Fulham,42,5,13,20,27:53,-26,28
18,19,West Brom,42,5,11,22,35:76,-41,26
19,20,Sheff Utd,42,7,2,29,20:63,-43,23

In [10]:
df.replace({'Man City': 'Manchester City', 'Man Utd': 'Manchester United', 'Sheff Utd': 'Sheffield United', 'Sheff Wed': 'Sheffield Wednesday', 'Nottm Forest': 'Nottingham Forest', 'QPR': 'Queens Park Rangers', 'Wolves': 'Wolverhampton Wanderers', 'Leeds': 'Leeds United', 'Ipswich': 'Ipswich Town', 'Coventry': 'Coventry City', 'Wimbledon FC': 'Wimbledon', 'Tottenham': 'Tottenham Hotspur', 'Norwich': 'Norwich City', 'Blackburn': 'Blackburn Rovers', 'Newcastle': 'Newcastle United', 'West Ham': 'West Ham United', 'Leicester': 'Leicester City', 'Bolton': 'Bolton Wanderers', 'Derby': 'Derby County', 'Barnsley FC': 'Barnsley', 'Charlton': 'Charlton Athletic', 'Bradford': 'Bradford City', 'West Brom': 'West Bromwich Albion', 'Birmingham': 'Birmingham City', 'Wolves': 'Wolverhampton Wanderers', 'Wigan': 'Wigan Athletic', 'Swansea': 'Swansea City', 'Cardiff': 'Cardiff City', 'Huddersfield': 'Huddersfield Town', 'Brighton': 'Brighton & Hove Albion'}, inplace=True)

In [11]:
# Close the driver
driver.quit()

In [12]:
df.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points
0,1,Manchester City,42,27,5,6,83:32,51,86
1,2,Manchester United,42,21,11,6,73:44,29,74
2,3,Liverpool,42,20,9,9,68:42,26,69
3,4,Chelsea,42,19,10,9,58:36,22,67
4,5,Leicester City,42,20,6,12,68:50,18,66
5,6,West Ham United,42,19,8,11,62:47,15,65
6,7,Tottenham Hotspur,42,18,8,12,68:45,23,62
7,8,Arsenal,42,18,7,13,55:39,16,61
8,9,Leeds United,42,18,5,15,62:54,8,59
9,10,Everton,42,17,8,13,47:48,-1,59
10,11,Aston Villa,42,16,7,15,55:46,9,55
11,12,Newcastle United,42,12,9,17,46:62,-16,45
12,13,Wolverhampton Wanderers,42,12,9,17,36:52,-16,45
13,14,Crystal Palace,42,12,8,18,41:66,-25,44
14,15,Southampton,42,12,7,19,47:68,-21,43
15,16,Brighton & Hove Albion,42,9,14,15,40:46,-6,41
16,17,Burnley,42,10,9,19,33:55,-22,39
17,18,Fulham,42,5,13,20,27:53,-26,28
18,19,West Bromwich Albion,42,5,11,22,35:76,-41,26
19,20,Sheffield United,42,7,2,29,20:63,-43,23

In [13]:
df2 = pd.read_csv("EPL Matches 1992_1993_2023_2024.csv", index_col=0)

In [14]:
def add_managers_to_league_table(matches_df, league_table_df, season):
    """
    Add a column to the league table dataframe with managers who managed each team during a given season.
    
    Args:
        matches_df (pd.DataFrame): The dataframe containing match data.
        league_table_df (pd.DataFrame): The league table dataframe.
        season (str): The season to look for managers (e.g., '1992/1993').
    
    Returns:
        pd.DataFrame: The updated league table dataframe with a new 'Manager' column.
    """
    # Filter matches for the provided season
    season_matches = matches_df[matches_df['Season'] == season]

    # Create an empty dictionary to hold team names and their corresponding managers
    team_managers = {}

    # Loop through each match to get managers for the home and away teams
    for _, match in season_matches.iterrows():
        # For Home Team
        home_team = match['Home_Team']
        home_manager = match['Manager_Home']
        
        if home_team not in team_managers:
            team_managers[home_team] = set()  # Use a set to avoid duplicates
        team_managers[home_team].add(home_manager)

        # For Away Team
        away_team = match['Away_Team']
        away_manager = match['Manager_Away']
        
        if away_team not in team_managers:
            team_managers[away_team] = set()  # Use a set to avoid duplicates
        team_managers[away_team].add(away_manager)
    
    # Now, for each team in the league table, find their managers and add to the new column
    managers_list = []
    
    for _, row in league_table_df.iterrows():
        team_name = row['Team']
        
        if team_name in team_managers:
            # Convert the set of managers to a sorted list, then to a string
            managers = ', '.join(sorted(team_managers[team_name]))
        else:
            managers = 'Unknown'
        
        managers_list.append(managers)

    # Add the new column to the league table dataframe
    league_table_df['Manager'] = managers_list

    return league_table_df

In [15]:
updated_league_table = add_managers_to_league_table(df2, df, '2020/2021')
updated_league_table.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager
0,1,Manchester City,42,27,5,6,83:32,51,86,Pep Guardiola
1,2,Manchester United,42,21,11,6,73:44,29,74,Ole Gunnar Solskjaer
2,3,Liverpool,42,20,9,9,68:42,26,69,Jurgen Klopp
3,4,Chelsea,42,19,10,9,58:36,22,67,"Frank Lampard, Thomas Tuchel"
4,5,Leicester City,42,20,6,12,68:50,18,66,Brendan Rodgers
5,6,West Ham United,42,19,8,11,62:47,15,65,David Moyes
6,7,Tottenham Hotspur,42,18,8,12,68:45,23,62,"Jose Mourinho, Ryan Mason"
7,8,Arsenal,42,18,7,13,55:39,16,61,Mikel Arteta
8,9,Leeds United,42,18,5,15,62:54,8,59,Marcelo Bielsa
9,10,Everton,42,17,8,13,47:48,-1,59,Carlo Ancelotti
10,11,Aston Villa,42,16,7,15,55:46,9,55,Dean Smith
11,12,Newcastle United,42,12,9,17,46:62,-16,45,Steve Bruce
12,13,Wolverhampton Wanderers,42,12,9,17,36:52,-16,45,Nuno Espirito Santo
13,14,Crystal Palace,42,12,8,18,41:66,-25,44,Roy Hodgson
14,15,Southampton,42,12,7,19,47:68,-21,43,Ralph Hasenhuttl
15,16,Brighton & Hove Albion,42,9,14,15,40:46,-6,41,Graham Potter
16,17,Burnley,42,10,9,19,33:55,-22,39,Sean Dyche
17,18,Fulham,42,5,13,20,27:53,-26,28,Scott Parker
18,19,West Bromwich Albion,42,5,11,22,35:76,-41,26,"Sam Allardyce, Slaven Bilic"
19,20,Sheffield United,42,7,2,29,20:63,-43,23,"Chris Wilder, Paul Heckingbottom"

In [16]:
df_manager = pd.read_csv("Manager History.csv")
team_id_mapping = dict(zip(df_manager['Team_Name'], df_manager['Team_ID']))
updated_league_table['Team_ID'] = updated_league_table['Team'].map(team_id_mapping)
updated_league_table.head(23)

,Position,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager,Team_ID
0,1,Manchester City,42,27,5,6,83:32,51,86,Pep Guardiola,MCI
1,2,Manchester United,42,21,11,6,73:44,29,74,Ole Gunnar Solskjaer,MUN
2,3,Liverpool,42,20,9,9,68:42,26,69,Jurgen Klopp,LIV
3,4,Chelsea,42,19,10,9,58:36,22,67,"Frank Lampard, Thomas Tuchel",CHE
4,5,Leicester City,42,20,6,12,68:50,18,66,Brendan Rodgers,LCI
5,6,West Ham United,42,19,8,11,62:47,15,65,David Moyes,WHA
6,7,Tottenham Hotspur,42,18,8,12,68:45,23,62,"Jose Mourinho, Ryan Mason",THO
7,8,Arsenal,42,18,7,13,55:39,16,61,Mikel Arteta,ARS
8,9,Leeds United,42,18,5,15,62:54,8,59,Marcelo Bielsa,LUN
9,10,Everton,42,17,8,13,47:48,-1,59,Carlo Ancelotti,EVE
10,11,Aston Villa,42,16,7,15,55:46,9,55,Dean Smith,AVI
11,12,Newcastle United,42,12,9,17,46:62,-16,45,Steve Bruce,NUN
12,13,Wolverhampton Wanderers,42,12,9,17,36:52,-16,45,Nuno Espirito Santo,WWA
13,14,Crystal Palace,42,12,8,18,41:66,-25,44,Roy Hodgson,CPA
14,15,Southampton,42,12,7,19,47:68,-21,43,Ralph Hasenhuttl,SOU
15,16,Brighton & Hove Albion,42,9,14,15,40:46,-6,41,Graham Potter,BHA
16,17,Burnley,42,10,9,19,33:55,-22,39,Sean Dyche,BUR
17,18,Fulham,42,5,13,20,27:53,-26,28,Scott Parker,FUL
18,19,West Bromwich Albion,42,5,11,22,35:76,-41,26,"Sam Allardyce, Slaven Bilic",WBR
19,20,Sheffield United,42,7,2,29,20:63,-43,23,"Chris Wilder, Paul Heckingbottom",SHU

In [17]:
updated_league_table['Season'] = '2020/2021'
updated_league_table = updated_league_table[['Season', 'Position', 'Team_ID', 'Team', 'Played', 'Wins', 'Draws', 'Losses', 'Goals', 'Goal Difference', 'Points', 'Manager']]
updated_league_table.head(23)

,Season,Position,Team_ID,Team,Played,Wins,Draws,Losses,Goals,Goal Difference,Points,Manager
0,2020/2021,1,MCI,Manchester City,42,27,5,6,83:32,51,86,Pep Guardiola
1,2020/2021,2,MUN,Manchester United,42,21,11,6,73:44,29,74,Ole Gunnar Solskjaer
2,2020/2021,3,LIV,Liverpool,42,20,9,9,68:42,26,69,Jurgen Klopp
3,2020/2021,4,CHE,Chelsea,42,19,10,9,58:36,22,67,"Frank Lampard, Thomas Tuchel"
4,2020/2021,5,LCI,Leicester City,42,20,6,12,68:50,18,66,Brendan Rodgers
5,2020/2021,6,WHA,West Ham United,42,19,8,11,62:47,15,65,David Moyes
6,2020/2021,7,THO,Tottenham Hotspur,42,18,8,12,68:45,23,62,"Jose Mourinho, Ryan Mason"
7,2020/2021,8,ARS,Arsenal,42,18,7,13,55:39,16,61,Mikel Arteta
8,2020/2021,9,LUN,Leeds United,42,18,5,15,62:54,8,59,Marcelo Bielsa
9,2020/2021,10,EVE,Everton,42,17,8,13,47:48,-1,59,Carlo Ancelotti
10,2020/2021,11,AVI,Aston Villa,42,16,7,15,55:46,9,55,Dean Smith
11,2020/2021,12,NUN,Newcastle United,42,12,9,17,46:62,-16,45,Steve Bruce
12,2020/2021,13,WWA,Wolverhampton Wanderers,42,12,9,17,36:52,-16,45,Nuno Espirito Santo
13,2020/2021,14,CPA,Crystal Palace,42,12,8,18,41:66,-25,44,Roy Hodgson
14,2020/2021,15,SOU,Southampton,42,12,7,19,47:68,-21,43,Ralph Hasenhuttl
15,2020/2021,16,BHA,Brighton & Hove Albion,42,9,14,15,40:46,-6,41,Graham Potter
16,2020/2021,17,BUR,Burnley,42,10,9,19,33:55,-22,39,Sean Dyche
17,2020/2021,18,FUL,Fulham,42,5,13,20,27:53,-26,28,Scott Parker
18,2020/2021,19,WBR,West Bromwich Albion,42,5,11,22,35:76,-41,26,"Sam Allardyce, Slaven Bilic"
19,2020/2021,20,SHU,Sheffield United,42,7,2,29,20:63,-43,23,"Chris Wilder, Paul Heckingbottom"

In [18]:
updated_league_table.to_csv('2020_2021 League Table.csv')